---
title: "MP3"
author: "Sneha Verma, Pema Choden, Tenzin Paldon"
date: "November 6, 2017"
output: html_document
---
##                 How Repetitive is Hollywood?
```{r, message=FALSE}
library(mdsr)
library(RMySQL)
library(tidyverse)
db <- dbConnect_scidb(dbname = "imdb")
```

```{r}
#Find movies (kind_id = 1) and are sequels (link_type_id = 1)

sql <- "SELECT t.id, title, kind_id, production_year, linked_movie_id, mi.info as genre, mi2.info as country
FROM imdb.title t
#joining movie_link and movie_info by id 
JOIN movie_link ml
	ON t.id = ml.movie_id
JOIN movie_info mi
  ON t.id = mi.movie_id
#second join with title and movie_info to see genre and country
JOIN movie_info mi2
  ON t.id = mi2.movie_id
WHERE kind_id = 1 AND 
      #movies that are only sequels
      ml.link_type_id = 1 AND
      #see genres of all movies
      mi.info_type_id = 3 AND
      #filter for only U.S made movies
      mi2.info = 'USA'
GROUP BY t.id
ORDER BY production_year;
"

#save sql as a dataframe in R
sequels <-db%>% 
  dbGetQuery(sql)
sequels
```

```{r}
#Adding the production_year of prequel

sql2 <- "SELECT id, title, production_year as prequel_release_year
FROM title
WHERE kind_id = 1 
Group by id
;"

prequel_release <- db%>%
  dbGetQuery(sql2)
prequel_release
```

```{r}
#Join sequels tbl and prequel_release tbl

movies <- sequels %>%
  #join so that the sequels are linked to their prequels
  inner_join(prequel_release, by = c("linked_movie_id" = "id")) %>%
  #rename columns to make tbl easier to read
  rename(title = title.x, prequel_title = title.y) %>%
  #look at movies after a certain time
  #filter(prequel_release_year >= 1950) %>%
  #find the time between orginal and sequels for each movie
  mutate(time_between_sequels = production_year - prequel_release_year)
```



